import { SCREEN_WIDTH_PROPOTIONS } from "./view.const.js";

const ROWS = 20;
const COLS = 10;

export const MAP_CONFIG = {
  size: { cols: COLS, rows: ROWS },
  points: {
    seats: [
      { col: 2, row: 1 },
      { col: 7, row: 1 },
      { col: 1, row: 3 },
      { col: 8, row: 2 },
      { col: 6, row: 5 },
      { col: 8, row: 5 },
      { col: 3, row: 6 },
      { col: 2, row: 7 },
      { col: 3, row: 9 },
      { col: 2, row: 10 },
      { col: 3, row: 13 },
      { col: 2, row: 14 },
      { col: 1, row: 15 },
      { col: 1, row: 16 },
      { col: 3, row: 18 },
      { col: 6, row: 18 },
    ],
    order: [
      { col: 5, row: 9 },
      { col: 5, row: 10 },
      { col: 5, row: 11 },
    ],
    doors: [
      { col: 4, row: 4 },
      { col: 5, row: 4 },
      { col: 7, row: 18 },
    ],
    objects: [
      { col: 1, row: 6 },
      { col: 2, row: 6 },
      { col: 1, row: 9 },
      { col: 2, row: 9 },
      { col: 1, row: 13 },
      { col: 2, row: 13 },
      { col: 8, row: 7 },
      { col: 6, row: 14 },
      { col: 7, row: 14 },
      { col: 8, row: 14 },
      { col: 8, row: 15 },
      { col: 6, row: 4 },
      { col: 7, row: 4 },
      { col: 8, row: 4 },
      { col: 3, row: 1 },
      { col: 6, row: 1 },
      { col: 2, row: 2 },
      { col: 7, row: 2 },
      { col: 0, row: 2 },
      { col: 9, row: 2 },
      { col: 6, row: 7 },
      { col: 7, row: 7 },
      { col: 7, row: 7 },
      { col: 6, row: 8 },
      { col: 7, row: 8 },
      { col: 6, row: 9 },
      { col: 7, row: 9 },
      { col: 6, row: 10 },
      { col: 7, row: 10 },
      { col: 4, row: 18 },
      { col: 5, row: 18 },
      { col: 1, row: 18 },
      { col: 2, row: 18 },
      { col: 7, row: 18 },
      { col: 8, row: 17 },
      { col: 8, row: 18 },
    ],
  },
  map: [
    { position: { col: 0, row: 0 } },
    { position: { col: 0, row: 1 } },
    { position: { col: 0, row: 2 } },
    { position: { col: 0, row: 3 } },
    { position: { col: 0, row: 4 } },
    { position: { col: 0, row: 5 } },
    { position: { col: 0, row: 6 } },
    { position: { col: 0, row: 7 } },
    { position: { col: 0, row: 8 } },
    { position: { col: 0, row: 9 } },
    { position: { col: 0, row: 10 } },
    { position: { col: 0, row: 11 } },
    { position: { col: 0, row: 12 } },
    { position: { col: 0, row: 13 } },
    { position: { col: 0, row: 14 } },
    { position: { col: 0, row: 15 } },
    { position: { col: 0, row: 16 } },
    { position: { col: 0, row: 17 } },
    { position: { col: 0, row: 18 } },
    { position: { col: 0, row: 19 } },
    { position: { col: 1, row: 0 } },
    { position: { col: 1, row: 1 } },
    { position: { col: 1, row: 2 } },
    { position: { col: 1, row: 3 } },
    { position: { col: 1, row: 4 } },
    { position: { col: 1, row: 5 } },
    { position: { col: 1, row: 6 } },
    { position: { col: 1, row: 7 } },
    { position: { col: 1, row: 8 } },
    { position: { col: 1, row: 9 } },
    { position: { col: 1, row: 10 } },
    { position: { col: 1, row: 11 } },
    { position: { col: 1, row: 12 } },
    { position: { col: 1, row: 13 } },
    { position: { col: 1, row: 14 } },
    { position: { col: 1, row: 15 } },
    { position: { col: 1, row: 16 } },
    { position: { col: 1, row: 17 } },
    { position: { col: 1, row: 18 } },
    { position: { col: 1, row: 19 } },
    { position: { col: 2, row: 0 } },
    { position: { col: 2, row: 1 } },
    { position: { col: 2, row: 2 } },
    { position: { col: 2, row: 3 } },
    { position: { col: 2, row: 4 } },
    { position: { col: 2, row: 5 } },
    { position: { col: 2, row: 6 } },
    { position: { col: 2, row: 7 } },
    { position: { col: 2, row: 8 } },
    { position: { col: 2, row: 9 } },
    { position: { col: 2, row: 10 } },
    { position: { col: 2, row: 11 } },
    { position: { col: 2, row: 12 } },
    { position: { col: 2, row: 13 } },
    { position: { col: 2, row: 14 } },
    { position: { col: 2, row: 15 } },
    { position: { col: 2, row: 16 } },
    { position: { col: 2, row: 17 } },
    { position: { col: 2, row: 18 } },
    { position: { col: 2, row: 19 } },
    { position: { col: 3, row: 0 } },
    { position: { col: 3, row: 1 } },
    { position: { col: 3, row: 2 } },
    { position: { col: 3, row: 3 } },
    { position: { col: 3, row: 4 } },
    { position: { col: 3, row: 5 } },
    { position: { col: 3, row: 6 } },
    { position: { col: 3, row: 7 } },
    { position: { col: 3, row: 8 } },
    { position: { col: 3, row: 9 } },
    { position: { col: 3, row: 10 } },
    { position: { col: 3, row: 11 } },
    { position: { col: 3, row: 12 } },
    { position: { col: 3, row: 13 } },
    { position: { col: 3, row: 14 } },
    { position: { col: 3, row: 15 } },
    { position: { col: 3, row: 16 } },
    { position: { col: 3, row: 17 } },
    { position: { col: 3, row: 18 } },
    { position: { col: 3, row: 19 } },
    { position: { col: 4, row: 0 } },
    { position: { col: 4, row: 1 } },
    { position: { col: 4, row: 2 } },
    { position: { col: 4, row: 3 } },
    { position: { col: 4, row: 4 } },
    { position: { col: 4, row: 5 } },
    { position: { col: 4, row: 6 } },
    { position: { col: 4, row: 7 } },
    { position: { col: 4, row: 8 } },
    { position: { col: 4, row: 9 } },
    { position: { col: 4, row: 10 } },
    { position: { col: 4, row: 11 } },
    { position: { col: 4, row: 12 } },
    { position: { col: 4, row: 13 } },
    { position: { col: 4, row: 14 } },
    { position: { col: 4, row: 15 } },
    { position: { col: 4, row: 16 } },
    { position: { col: 4, row: 17 } },
    { position: { col: 4, row: 18 } },
    { position: { col: 4, row: 19 } },
    { position: { col: 5, row: 0 } },
    { position: { col: 5, row: 1 } },
    { position: { col: 5, row: 2 } },
    { position: { col: 5, row: 3 } },
    { position: { col: 5, row: 4 } },
    { position: { col: 5, row: 5 } },
    { position: { col: 5, row: 6 } },
    { position: { col: 5, row: 7 } },
    { position: { col: 5, row: 8 } },
    { position: { col: 5, row: 9 } },
    { position: { col: 5, row: 10 } },
    { position: { col: 5, row: 11 } },
    { position: { col: 5, row: 12 } },
    { position: { col: 5, row: 13 } },
    { position: { col: 5, row: 14 } },
    { position: { col: 5, row: 15 } },
    { position: { col: 5, row: 16 } },
    { position: { col: 5, row: 17 } },
    { position: { col: 5, row: 18 } },
    { position: { col: 5, row: 19 } },
    { position: { col: 6, row: 0 } },
    { position: { col: 6, row: 1 } },
    { position: { col: 6, row: 2 } },
    { position: { col: 6, row: 3 } },
    { position: { col: 6, row: 4 } },
    { position: { col: 6, row: 5 } },
    { position: { col: 6, row: 6 } },
    { position: { col: 6, row: 7 } },
    { position: { col: 6, row: 8 } },
    { position: { col: 6, row: 9 } },
    { position: { col: 6, row: 10 } },
    { position: { col: 6, row: 11 } },
    { position: { col: 6, row: 12 } },
    { position: { col: 6, row: 13 } },
    { position: { col: 6, row: 14 } },
    { position: { col: 6, row: 15 } },
    { position: { col: 6, row: 16 } },
    { position: { col: 6, row: 17 } },
    { position: { col: 6, row: 18 } },
    { position: { col: 6, row: 19 } },
    { position: { col: 7, row: 0 } },
    { position: { col: 7, row: 1 } },
    { position: { col: 7, row: 2 } },
    { position: { col: 7, row: 3 } },
    { position: { col: 7, row: 4 } },
    { position: { col: 7, row: 5 } },
    { position: { col: 7, row: 6 } },
    { position: { col: 7, row: 7 } },
    { position: { col: 7, row: 8 } },
    { position: { col: 7, row: 9 } },
    { position: { col: 7, row: 10 } },
    { position: { col: 7, row: 11 } },
    { position: { col: 7, row: 12 } },
    { position: { col: 7, row: 13 } },
    { position: { col: 7, row: 14 } },
    { position: { col: 7, row: 15 } },
    { position: { col: 7, row: 16 } },
    { position: { col: 7, row: 17 } },
    { position: { col: 7, row: 18 } },
    { position: { col: 7, row: 19 } },
    { position: { col: 8, row: 0 } },
    { position: { col: 8, row: 1 } },
    { position: { col: 8, row: 2 } },
    { position: { col: 8, row: 3 } },
    { position: { col: 8, row: 4 } },
    { position: { col: 8, row: 5 } },
    { position: { col: 8, row: 6 } },
    { position: { col: 8, row: 7 } },
    { position: { col: 8, row: 8 } },
    { position: { col: 8, row: 9 } },
    { position: { col: 8, row: 10 } },
    { position: { col: 8, row: 11 } },
    { position: { col: 8, row: 12 } },
    { position: { col: 8, row: 13 } },
    { position: { col: 8, row: 14 } },
    { position: { col: 8, row: 15 } },
    { position: { col: 8, row: 16 } },
    { position: { col: 8, row: 17 } },
    { position: { col: 8, row: 18 } },
    { position: { col: 8, row: 19 } },
    { position: { col: 9, row: 0 } },
    { position: { col: 9, row: 1 } },
    { position: { col: 9, row: 2 } },
    { position: { col: 9, row: 3 } },
    { position: { col: 9, row: 4 } },
    { position: { col: 9, row: 5 } },
    { position: { col: 9, row: 6 } },
    { position: { col: 9, row: 7 } },
    { position: { col: 9, row: 8 } },
    { position: { col: 9, row: 9 } },
    { position: { col: 9, row: 10 } },
    { position: { col: 9, row: 11 } },
    { position: { col: 9, row: 12 } },
    { position: { col: 9, row: 13 } },
    { position: { col: 9, row: 14 } },
    { position: { col: 9, row: 15 } },
    { position: { col: 9, row: 16 } },
    { position: { col: 9, row: 17 } },
    { position: { col: 9, row: 18 } },
    { position: { col: 9, row: 19 } },
  ],
};
