const ROWS = 20;
const COLS = 10;

export const MAP_CONFIG = {
  size: { cols: COLS, rows: ROWS },
  points: {
    seats: [
      // { position: { col: 2, row: 1 } },
      // { position: { col: 7, row: 1 } },
      // { position: { col: 1, row: 2 } },
      // { position: { col: 8, row: 2 } },
      { position: { col: 6, row: 5 } },
      { position: { col: 8, row: 5 } },
      { position: { col: 3, row: 6 } },
      { position: { col: 2, row: 7 } },
      { position: { col: 3, row: 9 } },
      { position: { col: 2, row: 10 } },
      { position: { col: 3, row: 13 } },
      { position: { col: 2, row: 14 } },
      { position: { col: 1, row: 15 } },
      { position: { col: 1, row: 16 } },
      { position: { col: 3, row: 18 } },
      { position: { col: 6, row: 18 } },
      // dog seats
      { position: { col: 3, row: 16 }, characterLabels: ['dog'] },
      { position: { col: 5, row: 15 }, characterLabels: ['dog'] },
      { position: { col: 4, row: 8 }, characterLabels: ['dog'] },
      { position: { col: 4, row: 4 }, characterLabels: ['dog'] },
      { position: { col: 5, row: 4 }, characterLabels: ['dog'] },
    ],
    order: [
      { position: { col: 5, row: 9 } },
      { position: { col: 5, row: 10 } },
      { position: { col: 5, row: 11 } },
    ],
    doors: [
      { position: { col: 4, row: 3 } },
      { position: { col: 5, row: 3 } },
      // { position: { col: 7, row: 18 } },
    ],
    objects: [
      { position: { col: 1, row: 6 } },
      { position: { col: 2, row: 6 } },
      { position: { col: 1, row: 9 } },
      { position: { col: 2, row: 9 } },
      { position: { col: 1, row: 13 } },
      { position: { col: 2, row: 13 } },
      { position: { col: 8, row: 7 } },
      { position: { col: 6, row: 14 } },
      { position: { col: 7, row: 14 } },
      { position: { col: 8, row: 14 } },
      { position: { col: 8, row: 15 } },
      { position: { col: 6, row: 4 } },
      { position: { col: 7, row: 4 } },
      { position: { col: 8, row: 4 } },
      { position: { col: 3, row: 1 } },
      { position: { col: 6, row: 1 } },
      { position: { col: 2, row: 2 } },
      { position: { col: 7, row: 2 } },
      { position: { col: 0, row: 2 } },
      { position: { col: 9, row: 2 } },
      { position: { col: 6, row: 7 } },
      { position: { col: 7, row: 7 } },
      { position: { col: 7, row: 7 } },
      { position: { col: 6, row: 8 } },
      { position: { col: 7, row: 8 } },
      { position: { col: 6, row: 9 } },
      { position: { col: 7, row: 9 } },
      { position: { col: 6, row: 10 } },
      { position: { col: 7, row: 10 } },
      { position: { col: 4, row: 18 } },
      { position: { col: 5, row: 18 } },
      { position: { col: 1, row: 18 } },
      { position: { col: 2, row: 18 } },
      { position: { col: 7, row: 18 } },
      { position: { col: 8, row: 17 } },
      { position: { col: 8, row: 18 } },
    ],
  },
  map: [
    { position: { col: 0, row: 0 } },
    { position: { col: 0, row: 1 } },
    { position: { col: 0, row: 2 } },
    { position: { col: 0, row: 3 } },
    { position: { col: 0, row: 4 } },
    { position: { col: 0, row: 5 } },
    { position: { col: 0, row: 6 } },
    { position: { col: 0, row: 7 } },
    { position: { col: 0, row: 8 } },
    { position: { col: 0, row: 9 } },
    { position: { col: 0, row: 10 } },
    { position: { col: 0, row: 11 } },
    { position: { col: 0, row: 12 } },
    { position: { col: 0, row: 13 } },
    { position: { col: 0, row: 14 } },
    { position: { col: 0, row: 15 } },
    { position: { col: 0, row: 16 } },
    { position: { col: 0, row: 17 } },
    { position: { col: 0, row: 18 } },
    { position: { col: 0, row: 19 } },
    { position: { col: 1, row: 0 } },
    { position: { col: 1, row: 1 } },
    { position: { col: 1, row: 2 } },
    { position: { col: 1, row: 3 } },
    { position: { col: 1, row: 4 } },
    { position: { col: 1, row: 5 } },
    { position: { col: 1, row: 6 } },
    { position: { col: 1, row: 7 } },
    { position: { col: 1, row: 8 } },
    { position: { col: 1, row: 9 } },
    { position: { col: 1, row: 10 } },
    { position: { col: 1, row: 11 } },
    { position: { col: 1, row: 12 } },
    { position: { col: 1, row: 13 } },
    { position: { col: 1, row: 14 } },
    { position: { col: 1, row: 15 } },
    { position: { col: 1, row: 16 } },
    { position: { col: 1, row: 17 } },
    { position: { col: 1, row: 18 } },
    { position: { col: 1, row: 19 } },
    { position: { col: 2, row: 0 } },
    { position: { col: 2, row: 1 } },
    { position: { col: 2, row: 2 } },
    { position: { col: 2, row: 3 } },
    { position: { col: 2, row: 4 } },
    { position: { col: 2, row: 5 } },
    { position: { col: 2, row: 6 } },
    { position: { col: 2, row: 7 } },
    { position: { col: 2, row: 8 } },
    { position: { col: 2, row: 9 } },
    { position: { col: 2, row: 10 } },
    { position: { col: 2, row: 11 } },
    { position: { col: 2, row: 12 } },
    { position: { col: 2, row: 13 } },
    { position: { col: 2, row: 14 } },
    { position: { col: 2, row: 15 } },
    { position: { col: 2, row: 16 } },
    { position: { col: 2, row: 17 } },
    { position: { col: 2, row: 18 } },
    { position: { col: 2, row: 19 } },
    { position: { col: 3, row: 0 } },
    { position: { col: 3, row: 1 } },
    { position: { col: 3, row: 2 } },
    { position: { col: 3, row: 3 } },
    { position: { col: 3, row: 4 } },
    { position: { col: 3, row: 5 } },
    { position: { col: 3, row: 6 } },
    { position: { col: 3, row: 7 } },
    { position: { col: 3, row: 8 } },
    { position: { col: 3, row: 9 } },
    { position: { col: 3, row: 10 } },
    { position: { col: 3, row: 11 } },
    { position: { col: 3, row: 12 } },
    { position: { col: 3, row: 13 } },
    { position: { col: 3, row: 14 } },
    { position: { col: 3, row: 15 } },
    { position: { col: 3, row: 16 } },
    { position: { col: 3, row: 17 } },
    { position: { col: 3, row: 18 } },
    { position: { col: 3, row: 19 } },
    { position: { col: 4, row: 0 } },
    { position: { col: 4, row: 1 } },
    { position: { col: 4, row: 2 } },
    { position: { col: 4, row: 3 } },
    { position: { col: 4, row: 4 } },
    { position: { col: 4, row: 5 } },
    { position: { col: 4, row: 6 } },
    { position: { col: 4, row: 7 } },
    { position: { col: 4, row: 8 } },
    { position: { col: 4, row: 9 } },
    { position: { col: 4, row: 10 } },
    { position: { col: 4, row: 11 } },
    { position: { col: 4, row: 12 } },
    { position: { col: 4, row: 13 } },
    { position: { col: 4, row: 14 } },
    { position: { col: 4, row: 15 } },
    { position: { col: 4, row: 16 } },
    { position: { col: 4, row: 17 } },
    { position: { col: 4, row: 18 } },
    { position: { col: 4, row: 19 } },
    { position: { col: 5, row: 0 } },
    { position: { col: 5, row: 1 } },
    { position: { col: 5, row: 2 } },
    { position: { col: 5, row: 3 } },
    { position: { col: 5, row: 4 } },
    { position: { col: 5, row: 5 } },
    { position: { col: 5, row: 6 } },
    { position: { col: 5, row: 7 } },
    { position: { col: 5, row: 8 } },
    { position: { col: 5, row: 9 } },
    { position: { col: 5, row: 10 } },
    { position: { col: 5, row: 11 } },
    { position: { col: 5, row: 12 } },
    { position: { col: 5, row: 13 } },
    { position: { col: 5, row: 14 } },
    { position: { col: 5, row: 15 } },
    { position: { col: 5, row: 16 } },
    { position: { col: 5, row: 17 } },
    { position: { col: 5, row: 18 } },
    { position: { col: 5, row: 19 } },
    { position: { col: 6, row: 0 } },
    { position: { col: 6, row: 1 } },
    { position: { col: 6, row: 2 } },
    { position: { col: 6, row: 3 } },
    { position: { col: 6, row: 4 } },
    { position: { col: 6, row: 5 } },
    { position: { col: 6, row: 6 } },
    { position: { col: 6, row: 7 } },
    { position: { col: 6, row: 8 } },
    { position: { col: 6, row: 9 } },
    { position: { col: 6, row: 10 } },
    { position: { col: 6, row: 11 } },
    { position: { col: 6, row: 12 } },
    { position: { col: 6, row: 13 } },
    { position: { col: 6, row: 14 } },
    { position: { col: 6, row: 15 } },
    { position: { col: 6, row: 16 } },
    { position: { col: 6, row: 17 } },
    { position: { col: 6, row: 18 } },
    { position: { col: 6, row: 19 } },
    { position: { col: 7, row: 0 } },
    { position: { col: 7, row: 1 } },
    { position: { col: 7, row: 2 } },
    { position: { col: 7, row: 3 } },
    { position: { col: 7, row: 4 } },
    { position: { col: 7, row: 5 } },
    { position: { col: 7, row: 6 } },
    { position: { col: 7, row: 7 } },
    { position: { col: 7, row: 8 } },
    { position: { col: 7, row: 9 } },
    { position: { col: 7, row: 10 } },
    { position: { col: 7, row: 11 } },
    { position: { col: 7, row: 12 } },
    { position: { col: 7, row: 13 } },
    { position: { col: 7, row: 14 } },
    { position: { col: 7, row: 15 } },
    { position: { col: 7, row: 16 } },
    { position: { col: 7, row: 17 } },
    { position: { col: 7, row: 18 } },
    { position: { col: 7, row: 19 } },
    { position: { col: 8, row: 0 } },
    { position: { col: 8, row: 1 } },
    { position: { col: 8, row: 2 } },
    { position: { col: 8, row: 3 } },
    { position: { col: 8, row: 4 } },
    { position: { col: 8, row: 5 } },
    { position: { col: 8, row: 6 } },
    { position: { col: 8, row: 7 } },
    { position: { col: 8, row: 8 } },
    { position: { col: 8, row: 9 } },
    { position: { col: 8, row: 10 } },
    { position: { col: 8, row: 11 } },
    { position: { col: 8, row: 12 } },
    { position: { col: 8, row: 13 } },
    { position: { col: 8, row: 14 } },
    { position: { col: 8, row: 15 } },
    { position: { col: 8, row: 16 } },
    { position: { col: 8, row: 17 } },
    { position: { col: 8, row: 18 } },
    { position: { col: 8, row: 19 } },
    { position: { col: 9, row: 0 } },
    { position: { col: 9, row: 1 } },
    { position: { col: 9, row: 2 } },
    { position: { col: 9, row: 3 } },
    { position: { col: 9, row: 4 } },
    { position: { col: 9, row: 5 } },
    { position: { col: 9, row: 6 } },
    { position: { col: 9, row: 7 } },
    { position: { col: 9, row: 8 } },
    { position: { col: 9, row: 9 } },
    { position: { col: 9, row: 10 } },
    { position: { col: 9, row: 11 } },
    { position: { col: 9, row: 12 } },
    { position: { col: 9, row: 13 } },
    { position: { col: 9, row: 14 } },
    { position: { col: 9, row: 15 } },
    { position: { col: 9, row: 16 } },
    { position: { col: 9, row: 17 } },
    { position: { col: 9, row: 18 } },
    { position: { col: 9, row: 19 } },
  ],
};
